JDO-789: Cleanup jdo-site pom
apache/db-jdo-site pull request #33
Opened 2021-02-28 19:04 UTC by mboapache

Here are the updates of the pom.xml:
- Added Apache License
- Added Apache parent pom
- Changed groupId to org.apache.jdo (same as db-jdo)
- Changed artifactId to jdo-site
- Changed version to 3.2-SNAPSHOT (same as db-jdo)
- Changed name to Apache JDO Site
- Added description
- Fixed url
- Added organization
- Added scm block with gitbox url
- Updated dependency of asciidoctor maven plugin to most recent version 
- Removed commented out line

Please note the update to version 2 of asciidoctor maven plugin requires some configuration changes.
Also when converting glossary.adoc asciidoctor prints three info messages, which are false positive:
INFO: possible invalid reference: application-identity

I also updated the copyright notice in the template to include 2021

2021-02-28 19:44 UTC, tobous requested changes
I have a couple of notes:

First of all, this change breaks the deploy workflow, meaning it also has to be adjusted as part of this PR.
The workflow works under the explicit assumption that the target directory only contains the `site` directory after the clean build. I added the assumption to check whether there are any resources left that were not automatically moved to another location, indicating that the workflow is misconfigured and forgot something that is supposed to be deployed.
I can adjust the action to match the new behavior if you would like. I would just restrict the check to the `target/site` directory instead of the whole `target` directory and discard any other remaining resources in the `target` directory.

Secondly, as a heads-up: The update of the AsciiDoc version causes a large amount of changes to the build artifacts. But from having a look at them, there are only very slight differences (mostly regarding spacing) as far as I can tell. See attached diff for all changes:
[post-update-diff.txt](https://github.com/apache/db-jdo-site/files/6057803/post-update-diff.txt)

Thirdly, regarding the version number: The website is a rolling release so I don't think specifying a version really makes sense. Using the JDO version only creates additional work having to remember to update the pom for each new release. I would suggest just specifying version `1.0.0` as a default. As the pom is not set up to create any kind of release artifacts, the version number shouldn't matter anyways.

Lastly, as a process-related question: Did you add the link to the PR to the Jira ticket manually? I am just wondering because the required syntax for auto-linking would be `[JDO-789]` if I understand the wiki correctly.

2021-02-28 19:44 UTC, tobous commented on pom.xml
> +    <url>http://db.apache.org/jdo</url>
```suggestion
    <url>https://db.apache.org/jdo</url>
```

2021-02-28 19:44 UTC, tobous commented on pom.xml
> +        <url>http://www.apache.org</url>
```suggestion
        <url>https://www.apache.org</url>
```

2021-02-28 19:44 UTC, tobous commented on pom.xml
>                              <endpoint-url>http://db.apache.org/jdo</endpoint-url>
```suggestion
                            <endpoint-url>https://db.apache.org/jdo</endpoint-url>
```

2021-02-28 22:10 UTC, mboapache commented
> First of all, this change breaks the deploy workflow, meaning it also has to be adjusted as part of this PR.
> The workflow works under the explicit assumption that the target directory only contains the `site` directory after the clean build. I added the assumption to check whether there are any resources left that were not automatically moved to another location, indicating that the workflow is misconfigured and forgot something that is supposed to be deployed.
> I can adjust the action to match the new behavior if you would like. I would just restrict the check to the `target/site` directory instead of the whole `target` directory and discard any other remaining resources in the `target` directory.

Yes, I saw an additional directory being created under target. 
So it would be nice if you could adjust the action to work on target/site only.
 
> Secondly, as a heads-up: The update of the AsciiDoc version causes a large amount of changes to the build artifacts. But from having a look at them, there are only very slight differences (mostly regarding spacing) as far as I can tell. See attached diff for all changes:
> [post-update-diff.txt](https://github.com/apache/db-jdo-site/files/6057803/post-update-diff.txt)

Thanks for the diff. Most of the changes seem to be OK, but I haven't checked it in detail.

> Thirdly, regarding the version number: The website is a rolling release so I don't think specifying a version really makes sense. Using the JDO version only creates additional work having to remember to update the pom for each new release. I would suggest just specifying version `1.0.0` as a default. As the pom is not set up to create any kind of release artifacts, the version number shouldn't matter anyways.

If we use a different version number as db-jdo, we might also want to change the groupId being different from db-jdo. But I still think we should use the same version number as the db-jdo repository.

> 
> Lastly, as a process-related question: Did you add the link to the PR to the Jira ticket manually? I am just wondering because the required syntax for auto-linking would be `[JDO-789]` if I understand the wiki correctly.

No I did not add the link manually, so using the syntax JDO-789 (w/o square brackets) seems to work.

2021-03-04 20:08 UTC, tobous approved these changes

2021-03-07 09:26 UTC, merged